---
- import_tasks: roles/postgres/tasks/database_manager.yml
  vars:
    database_name: "{{keycloak_database}}"
    database_user: "{{keycloak_database_user}}"
    database_password: "{{keycloak_database_password}}"
  tags: keycloak

- name: Create Keycloak Docker Container
  docker_container:
    name: keycloak
    image: "jboss/keycloak:{{keycloak_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      DB_VENDOR: "postgres"
      DB_ADDR: "database"
      DB_PORT: "5432"
      DB_DATABASE: "{{keycloak_database}}"
      DB_USER: "{{keycloak_database_user}}"
      DB_PASSWORD: "{{keycloak_database_password}}"
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_HOSTNAME: "auth.{{project_tld}}"
      KEYCLOAK_USER: "{{keycloak_user}}"
      KEYCLOAK_PASSWORD: "{{keycloak_user_password}}"
    labels:
      traefik.http.routers.keycloak.entrypoints: "websecure"
      traefik.http.routers.keycloak.tls: "true"
      traefik.http.routers.keycloak.rule: "Host(`auth.{{project_tld}}`)"
      traefik.http.routers.keycloak.service: "keycloak"
      traefik.http.services.keycloak.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags: keycloak

- name: Create FreeIPA Directory
  file:
    path: "{{project_directory}}/freeipa"
    state: directory
  tags:
    - freeipa
    - keycloak

- name: Create FreeIPA Docker Container
  docker_container:
    name: freeipa
    image: "freeipa/freeipa-server:{{freeipa_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/freeipa:/data"
    labels:
      traefik.http.routers.freeipa.entrypoints: "websecure"
      traefik.http.routers.freeipa.tls: "true"
      traefik.http.routers.freeipa.rule: "Host(`ldap.{{project_tld}}`)"
      traefik.http.routers.freeipa.service: "freeipa"
      traefik.http.services.freeipa.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags:
    - freeipa
    - keycloak