---
- name: Create Jellyfin Directory
  file:
    path: "{{project_directory}}/jellyfin"
    state: directory
  tags: jellyfin

- name: Jellyfin Configuration File
  template:
    src: system.xml.j2
    dest: "{{project_directory}}/jellyfin/system.xml"
  tags: jellyfin
  notify: restart jellyfin

- name: Create Jellyfin Docker Container
  docker_container:
    name: jellyfin
    hostname: jellyfin
    image: "linuxserver/jellyfin:{{jellyfin_version}}"
    pull: yes
    restart_policy: unless-stopped
    comparisons:
      labels: allow_more_present
      '*': strict
    published_ports:
      - 8096:8096
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      PUID: "{{media_user}}"
      PGID: "{{media_group}}"
      TZ: "{{default_timezone}}"
    volumes:
      - "{{project_directory}}/jellyfin:/config"
      - "{{media_directory}}/movies:/media/movies"
      - "{{media_directory}}/tv:/media/tv"
      - "{{media_directory}}/fights:/media/fights"
      - "{{media_directory}}/books:/media/books"
      - "{{media_directory}}/audiobooks:/media/audiobooks"
      - "{{media_directory}}/podcasts:/media/podcasts"
      - "{{media_directory}}/music:/media/music"
      - "{{media_directory}}/kids:/media/kids"
      - /cache:/cache
    labels:
      traefik.http.routers.jellyfin.entrypoints: "websecure"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.rule: "Host(`{{jellyfin_tld}}`)"
      traefik.http.routers.jellyfin.service: "jellyfin"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
      traefik.enable: "true"
  tags: jellyfin
