---
- name: Create InspIRCd Directory
  file:
    path: "{{project_directory}}/inspircd"
    state: directory
  tags: inspircd

- name: Create InspIRCd Docker Container
  docker_container:
    name: inspircd
    image: "inspircd/inspircd-docker:{{inspircd_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      INSP_NET_SUFFIX: ""
      INSP_NET_NAME: ""
      INSP_SERVER_NAME: ""
      INSP_ADMIN_NAME: ""
      INSP_ADMIN_NICK: ""
      INSP_ADMIN_EMAIL: "support@{{project_tld}}"
    volumes:
      - "{{project_directory}}/inspircd:/inspircd/conf/"
    labels:
      traefik.tcp.routers.inspircd.rule: "HostSNI(`irc.{{chat_tld}}`)"
      traefik.tcp.routers.inspircd.service: "inspircd"
      traefik.tcp.services.inspircd.loadbalancer.server.address: "inspircd:6667"
      traefik.enable: "true"
  tags: inspircd
