---
- name: Create AllTube Directory
  file:
    path: "{{project_directory}}/alltube"
    state: directory
  tags: alltube

- name: Create AllTube Docker Container
  docker_container:
    name: alltube
    image: "{{registry_host}}/{{registry_username}}/docker-alltube:{{alltube_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    labels:
      traefik.http.routers.alltube.entrypoints: "websecure"
      traefik.http.routers.alltube.tls: "true"
      traefik.http.routers.alltube.rule: "Host(`alltube.{{project_tld}}`)"
      traefik.http.routers.alltube.middlewares: "default-headers@file"
      traefik.http.routers.alltube.service: "alltube"
      traefik.http.services.alltube.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: alltube