---
- name: Create Webdav Directory
  file:
    path: "{{project_directory}}/webdav"
    state: directory
  tags: webdav

- name: Create Webdav Docker Container
  docker_container:
    name: webdav
    image: "bytemark/webdav:{{webdav_version}}"
    pull: yes
    env:
      AUTH_TYPE: "Digest"
      USERNAME: "{{webdav_user}}"
      PASSWORD: "{{webdav_user_password}}"
      restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    volumes:
      - "{{project_directory}}/webdav:/var/lib/dav"
    state: started
    labels:
      traefik.http.routers.webdav.entrypoints: "websecure"
      traefik.http.routers.webdav.tls: "true"
      traefik.http.routers.webdav.rule: "Host(`webdav.{{project_tld}}`)"
      traefik.http.routers.webdav.middlewares: "default-headers@file"
      traefik.http.routers.webdav.service: "webdav"
      traefik.http.services.webdav.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: webdav